config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:registration], controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root 'logged_in#dashboard'
  get :help, to: 'logged_in#help'
  get :pcc, to: 'logged_in#pcc'

  namespace :admin do
    resources :lates
    resources :feedbacks, only: [:index]
    resources :leaves do
      member do
        patch 'approve'
        get 'reject'
        patch 'reject_action'
      end
    end
    resources :settings
    resources :staffs do
      resources :leaves, only: [:index], controller: 'staffs/leaves'
      resources :lates, only: [:index], controller: 'staffs/lates'
      resources :versions, only: [:index], controller: 'staffs/versions'
    end
  end

  namespace :staff do
    get 'profile', to: 'staffs#show'
    resources :leaves, only: [:index, :new, :create, :show]
    resources :lates, only: [:index]
  end

  resources :feedbacks, only: [:new, :create]
  resource :annuals do
    collection do
      get 'add_annual_leave_days'
    end
  end

end

app/models/staff.rb
class Staff < User

  scope :to_options, -> { all.collect { |staff| [ staff.english_name, staff.id ] } }
  scope :emails_cc, -> { all.collect { |staff| [ staff.english_name, staff.email ] } }
  scope :emails_cc_exclude, -> (staff_id) { where('id NOT IN (:staff_id)', {staff_id: staff_id}).collect { |staff| [ staff.english_name, staff.email ] } }
  scope :leaders, -> { where(is_leader: :true) }

  has_many :leaves
  has_many :lates
  has_many :feedbacks
  has_many :leave_days, through: :leaves

  def remaining_leave_days(year)
    self.leaves.in_year(year).annual.approved.sum(:total)
  end

  def remaining_sick_days(year)
    self.leaves.in_year(year).sick.approved.sum(:total)
  end
  
end

app/controllers/admin/staffs/lates_controller.rb
class Admin::Staffs::LatesController < Admin::BaseController

  def index
    @staff = Staff.find(staff_id)
    @lates = @staff.lates.paginate(page: page)
    render :index
  end

  protected
  def staff_id
    params.require(:staff_id)
  end

  def page
    params[:page]
  end
end

app/controllers/admin/staffs/leaves_controller.rb
class Admin::Staffs::LeavesController < Admin::BaseController 

  def index
    @staff = Staff.find(staff_id)
    @leaves = @staff.leaves.paginate(page: page)
  end

  protected
  def page
    params[:page]
  end

  def staff_id
    params.require(:staff_id)
  end
end

app/controllers/admin/staffs/versions_controller.rb
class Admin::Staffs::VersionsController < Admin::BaseController
  def index
    @staff = Staff.find(staff_id)
    @versions = @staff.versions.paginate(page: page)
  end

  protected
  def page
    params[:page]
  end

  def staff_id
    params.require(:staff_id)
  end

end

app/controllers/admin/staffs_controller.rb
class Admin::StaffsController < Admin::BaseController
  def index
    @staffs = Staff.paginate(page: page)
  end

  def new
    @staff = Staff.new
  end

  def create
    @staff = Staff.new(staff_param)

    if @staff.save
      redirect_to admin_staffs_path, notice: t('.message.success')
    else
      flash[:alert] = t('.message.failure')
      render :new
    end
  end

  def edit
    @staff = Staff.find(staff_id)
  end

  def update
    @staff = Staff.find(staff_id)
    if @staff.update(staff_param)
      redirect_to admin_staffs_path, notice: t('.message.success')
    else
      flash[:alert] = @staff.errors.full_messages.join('<br>').html_safe
      render :edit
    end
  end

  def destroy
    @staff = Staff.find(staff_id)

    if @staff.destroy
      redirect_to admin_staffs_path, notice: t('.message.success')
    else
      flash[:alert] = t('.message.failure')
      render :index
    end
  end

  def show
    @staff = Staff.find(staff_id)
    @leaves = @staff.leaves.limit(5)
    @lates = @staff.lates.limit(5)
    @versions = @staff.versions.limit(5)
  end

  protected
  def page
    params[:page]
  end

  def staff_id
    params.require(:id)
  end

  def staff_param
    params.require(:staff).permit(:email, :name, :english_name, :personal_email, :address, :birthday, :note, :social_insurance, :phone_number, :started_on, :probation_end_on, :password, :password_confirmation, :designation, :is_admin, :is_leader, :leader_id)
  end
end

app/controllers/staff/base_controller.rb
class Staff::BaseController < LoggedInController
  protected
  def current_staff
    current_user.becomes(Staff)
  end
end

app/controllers/staff/lates_controller.rb
class Staff::LatesController < Staff::BaseController
  def index
    @staff = current_staff
    @lates = @staff.lates.paginate(page: page)
    render :index
  end

  protected
  def page
    params[:page]
  end
end

app/controllers/staff/leaves_controller.rb
class Staff::LeavesController < Staff::BaseController
  def index
    @leaves = current_staff.leaves.order(start_day: :desc).paginate(page: page)
  end

  def new
    @leave = Leave.new
    @leader = User.find(current_staff.leader) if current_staff.leader.presence
  end

  def create
    @leave = Leave.new(leave_param.merge(staff: current_staff))

    if @leave.save
      LeaveNotifier.new_leave(@leave).deliver
      LeaveNotifier.warning_3_least_days(@leave).deliver if @leave.category.annual? && UtilDate.business_days_between(Date.today, @leave.start_day.to_date) < 3
      redirect_to staff_leaves_path, notice: t('.message.success')
    else
      flash[:alert] = t('.message.failure')
      render :new
    end
  end

  def show
    @leave = Leave.find(leave_id)
  end

  protected
  def page
    params[:page]
  end

  def leave_id
    params.require(:id)
  end

  def leave_param
    params.require(:leave).permit(:reason, :category, :start_date, :end_date, :start_time, :end_time, :total_value, :reason_note, emails_cc:[])
  end
end

app/controllers/staff/staffs_controller.rb
class Staff::StaffsController < Staff::BaseController
  def show
    @staff = Staff.find(current_user)
    @leaves = @staff.leaves.limit(5)
    @lates = @staff.lates.limit(5)
  end
end

app/views/staffs/_form.slim
= form_for staff do |f|
  .form-group
    = f.label :name, class: 'control-label'
    br
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :english_name, class: 'control-label'
    br
    = f.text_field :english_name, class: 'form-control'
  .form-group
    = f.label :email, class: 'control-label'
    br
    = f.email_field :email, class: 'form-control'
  .form-group
    = f.label :personal_email, class: 'control-label'
    br
    = f.email_field :personal_email, class: 'form-control'
  .form-group
    = f.label :birthday, class: 'control-label'
    br
    = f.date_field :birthday, class: 'form-control'
  .form-group
    = f.label :address, class: 'control-label'
    br
    = f.text_area :address, class: 'form-control'
  .form-group
    = f.label :phone_number, class: 'control-label'
    br
    = f.number_field :phone_number, class: 'form-control'
  .form-group
    = f.label :basic_salary, class: 'control-label'
    br
    = f.number_field :basic_salary, class: 'form-control'
  .form-group
    = f.label :pay_increment, class: 'control-label'
    br
    = f.number_field :pay_increment, class: 'form-control'
  .form-group
    = f.label :social_insurance, class: 'control-label'
    br
    = f.text_field :social_insurance, class: 'form-control'
  .form-group
    = f.label :started_on, class: 'control-label'
    br
    = f.date_field :started_on, class: 'form-control'
  .form-group
    = f.label :probation_end_on, class: 'control-label'
    br
    = f.date_field :probation_end_on, class: 'form-control'
  .form-group
    = f.label :note, class: 'control-label'
    br
    = f.text_area :note, class: 'form-control'
  .form-group
    = f.label :password, class: 'control-label'
    br
    = f.password_field :password, class: 'form-control'
  .form-group
    = f.label :password_confirmation, class: 'control-label'
    br
    = f.password_field :password_confirmation, class: 'form-control'
  = f.submit 'Submit', class: 'btn-u'
  = link_to 'Back', staffs_path, class: 'btn-u btn-u-default'

app/views/staffs/new.slim
= display_page_title('Add new staff')

.container.content
  .col-md-6
    = render partial: 'staffs/form', locals: { staff: staff }