config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:registration], controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root 'logged_in#dashboard'
  get :help, to: 'logged_in#help'
  get :pcc, to: 'logged_in#pcc'

  namespace :admin do
    resources :lates
    resources :feedbacks, only: [:index]
    resources :leaves do
      member do
        patch 'approve'
        get 'reject'
        patch 'reject_action'
      end
    end
    resources :settings
    resources :staffs do
      resources :leaves, only: [:index], controller: 'staffs/leaves'
      resources :lates, only: [:index], controller: 'staffs/lates'
      resources :versions, only: [:index], controller: 'staffs/versions'
    end
  end

  namespace :staff do
    get 'profile', to: 'staffs#show'
    resources :leaves, only: [:index, :new, :create, :show]
    resources :lates, only: [:index]
  end

  resources :feedbacks, only: [:new, :create]
  resource :annuals do
    collection do
      get 'add_annual_leave_days'
    end
  end

end

app/models/staff.rb
class Staff < User

  scope :to_options, -> { all.collect { |staff| [ staff.english_name, staff.id ] } }
  scope :emails_cc, -> { all.collect { |staff| [ staff.english_name, staff.email ] } }
  scope :emails_cc_exclude, -> (staff_id) { where('id NOT IN (:staff_id)', {staff_id: staff_id}).collect { |staff| [ staff.english_name, staff.email ] } }
  scope :leaders, -> { where(is_leader: :true) }

  has_many :leaves
  has_many :lates
  has_many :feedbacks
  has_many :leave_days, through: :leaves

  def remaining_leave_days(year)
    self.leaves.in_year(year).annual.approved.sum(:total)
  end

  def remaining_sick_days(year)
    self.leaves.in_year(year).sick.approved.sum(:total)
  end
  
end

app/controllers/admin/staffs/lates_controller.rb
class Admin::Staffs::LatesController < Admin::BaseController

  def index
    @staff = Staff.find(staff_id)
    @lates = @staff.lates.paginate(page: page)
    render :index
  end

  protected
  def staff_id
    params.require(:staff_id)
  end

  def page
    params[:page]
  end
end

app/controllers/admin/staffs/leaves_controller.rb
class Admin::Staffs::LeavesController < Admin::BaseController 

  def index
    @staff = Staff.find(staff_id)
    @leaves = @staff.leaves.paginate(page: page)
  end

  protected
  def page
    params[:page]
  end

  def staff_id
    params.require(:staff_id)
  end
end

app/controllers/admin/staffs/versions_controller.rb
class Admin::Staffs::VersionsController < Admin::BaseController
  def index
    @staff = Staff.find(staff_id)
    @versions = @staff.versions.paginate(page: page)
  end

  protected
  def page
    params[:page]
  end

  def staff_id
    params.require(:staff_id)
  end

end

app/controllers/admin/staffs_controller.rb
class Admin::StaffsController < Admin::BaseController
  def index
    @staffs = Staff.paginate(page: page)
  end

  def new
    @staff = Staff.new
  end

  def create
    @staff = Staff.new(staff_param)

    if @staff.save
      redirect_to admin_staffs_path, notice: t('.message.success')
    else
      flash[:alert] = t('.message.failure')
      render :new
    end
  end

  def edit
    @staff = Staff.find(staff_id)
  end

  def update
    @staff = Staff.find(staff_id)
    if @staff.update(staff_param)
      redirect_to admin_staffs_path, notice: t('.message.success')
    else
      flash[:alert] = @staff.errors.full_messages.join('<br>').html_safe
      render :edit
    end
  end

  def destroy
    @staff = Staff.find(staff_id)

    if @staff.destroy
      redirect_to admin_staffs_path, notice: t('.message.success')
    else
      flash[:alert] = t('.message.failure')
      render :index
    end
  end

  def show
    @staff = Staff.find(staff_id)
    @leaves = @staff.leaves.limit(5)
    @lates = @staff.lates.limit(5)
    @versions = @staff.versions.limit(5)
  end

  protected
  def page
    params[:page]
  end

  def staff_id
    params.require(:id)
  end

  def staff_param
    params.require(:staff).permit(:email, :name, :english_name, :personal_email, :address, :birthday, :note, :social_insurance, :phone_number, :started_on, :probation_end_on, :password, :password_confirmation, :designation, :is_admin, :is_leader, :leader_id)
  end
end

app/controllers/staff/base_controller.rb
class Staff::BaseController < LoggedInController
  protected
  def current_staff
    current_user.becomes(Staff)
  end
end

app/controllers/staff/lates_controller.rb
class Staff::LatesController < Staff::BaseController
  def index
    @staff = current_staff
    @lates = @staff.lates.paginate(page: page)
    render :index
  end

  protected
  def page
    params[:page]
  end
end

app/controllers/staff/leaves_controller.rb
class Staff::LeavesController < Staff::BaseController
  def index
    @leaves = current_staff.leaves.order(start_day: :desc).paginate(page: page)
  end

  def new
    @leave = Leave.new
    @leader = User.find(current_staff.leader) if current_staff.leader.presence
  end

  def create
    @leave = Leave.new(leave_param.merge(staff: current_staff))

    if @leave.save
      LeaveNotifier.new_leave(@leave).deliver
      LeaveNotifier.warning_3_least_days(@leave).deliver if @leave.category.annual? && UtilDate.business_days_between(Date.today, @leave.start_day.to_date) < 3
      redirect_to staff_leaves_path, notice: t('.message.success')
    else
      flash[:alert] = t('.message.failure')
      render :new
    end
  end

  def show
    @leave = Leave.find(leave_id)
  end

  protected
  def page
    params[:page]
  end

  def leave_id
    params.require(:id)
  end

  def leave_param
    params.require(:leave).permit(:reason, :category, :start_date, :end_date, :start_time, :end_time, :total_value, :reason_note, emails_cc:[])
  end
end

app/controllers/staff/staffs_controller.rb
class Staff::StaffsController < Staff::BaseController
  def show
    @staff = Staff.find(current_user)
    @leaves = @staff.leaves.limit(5)
    @lates = @staff.lates.limit(5)
  end
end

app/views/staff/staffs/show.slim
.table-wrapper.col-md-12
  h1 Your Account
  table.table.table-hover
    tr
      th.col-md-3=User.human_attribute_name('name')
      td= @staff.name
    tr
      th=User.human_attribute_name('english_name')
      td= @staff.english_name
    tr
      th=User.human_attribute_name('email')
      td= @staff.email
    tr
      th=User.human_attribute_name('personal_email')
      td= @staff.personal_email
    tr
      th=User.human_attribute_name('birthday')
      td= ldate(@staff.birthday)
    tr
      th=User.human_attribute_name('address')
      td= @staff.address
    tr
      th=User.human_attribute_name('phone_number')
      td= @staff.phone_number
    tr
      th=User.human_attribute_name('social_insurance')
      td= @staff.social_insurance
    tr
      th=User.human_attribute_name('started_on')
      td= ldate(@staff.started_on)
    tr
      th=User.human_attribute_name('probation_end_on')
      td= ldate(@staff.probation_end_on)
    tr
      th=User.human_attribute_name('note')
      td= @staff.note
    tr
      td{ colspan="2" }
        p= "Your leave days left #{pluralize(to_unsigned_integer(@staff.remaining_leave_days(Time.now.year)), 'day')} in this year"
        p= "Your sick leave days left #{pluralize(to_unsigned_integer(@staff.remaining_sick_days(Time.now.year)), 'day')} in this year"

  h1 Your List of Leaves
  table.table.table-hover
    thead
      th= 'No.'
      th= Leave.human_attribute_name('status')
      th= Leave.human_attribute_name('category')
      th= Leave.human_attribute_name('day')
      th= Leave.human_attribute_name('total')
      th= Leave.human_attribute_name('reason')
    tbody
      - @leaves.each_with_index do |leave, index|
        tr
          td= index + 1
          td= leave.status.text
          td= leave.category.text
          td
            strong= 'Start'
            = ": #{ldate(leave.start_day.to_date)} #{leave.start_time}"
            br
            strong= 'End'
            = "  : #{ldate(leave.end_day.to_date)} #{leave.end_time}"
          td= pluralize(leave.total.abs, 'day')
          td= leave.reason
  = link_to 'View all your leaves', staff_leaves_path, class: 'btn btn-info'

  h1 Your List of Lates
  table.table.table-hover
    thead
      th= 'No.'
      th= Late.human_attribute_name('date')
      th= Late.human_attribute_name('note')
    tbody
      - @lates.each_with_index do |late, index|
        tr
          td= index + 1
          td= ldate(late.date)
          td= late.note
  = link_to 'View all your lates', staff_lates_path, class: 'btn btn-info'